apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-api
  namespace: fcg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: games-api
  template:
    metadata:
      labels:
        app: games-api
    spec:
      containers:
      - name: games-api
        image: 536765581095.dkr.ecr.us-east-2.amazonaws.com/fcg-games@sha256:a940c56fd8bb091334fe1e46eb9c01debd84b3054e06ec37b6672b126f0b0105
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: ConnectionStrings__GamesDb
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: conn-games
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: jwt-issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: jwt-audience
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: fcg-secrets
              key: jwt-key
        - name: Search__UseOpenSearch
          value: 'false'
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: games-api
  namespace: fcg
spec:
  type: LoadBalancer
  selector:
    app: games-api
  ports:
  - port: 80
    targetPort: 8080
